<a href="https://colab.research.google.com/github/dsalvat/art-of-data-driven-business/blob/main/01b_TheArtofDataDrivenBusiness.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
d = {'col1': [1,5.8,2], 'col2': [3, 3.7, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0   1.0   3.0
1   5.8   3.7
2   2.0   4.0

In [4]:
df = pd.DataFrame({'Animal': ['Dog', 'Dog', 
                              'Rat', 'Rat', 'Rat'], 
                   'Max Speed': [380.,370.,24., 26., 25.], 
                   'Max Weight': [10.,8.1, .1,.12, .09]
                   }
                  )
df

  Animal  Max Speed  Max Weight
0    Dog      380.0       10.00
1    Dog      370.0        8.10
2    Rat       24.0        0.10
3    Rat       26.0        0.12
4    Rat       25.0        0.09

In [5]:
df.groupby(['Animal']).mean()

        Max Speed  Max Weight
Animal
Dog         375.0    9.050000
Rat          25.0    0.103333

In [6]:
df.value_counts()

Animal  Max Speed  Max Weight
Dog     370.0      8.10          1
        380.0      10.00         1
Rat     24.0       0.10          1
        25.0       0.09          1
        26.0       0.12          1
dtype: int64

In [7]:
df.agg("mean",axis="rows", numeric_only=True)

Max Speed     165.000
Max Weight      3.682
dtype: float64

In [8]:
df.agg({'Max Speed': ['sum', 'min'], 'Max Weight': ['mean', 'max']})

      Max Speed  Max Weight
sum       825.0         NaN
min        24.0         NaN
mean        NaN       3.682
max         NaN      10.000

In [9]:
df.quantile(.1)

Max Speed     24.400
Max Weight     0.094
Name: 0.1, dtype: float64

In [11]:
df.quantile([.1, .5])

     Max Speed  Max Weight
0.1       24.4       0.094
0.5       26.0       0.120

In [13]:
df = pd.DataFrame(
    {'type': ['one', 'one', 'one', 'two', 'two', 'two'],
     'cat': ['A', 'B', 'C', 'A','B','C'],
     'val': [1,2,3,4,5,6],
     'letter': ['x','y','z','q', 'w', 't']}
)
df.pivot(index='type', columns='cat', values='val')

cat   A  B  C
type
one   1  2  3
two   4  5  6